// Run with a Playwright-compatible page. All assertions inspect visible UI.
// Codex browser: runReviewJourney(tab.playwright), whose domSnapshot is supported.
export async function runReviewJourney(page) {
 const click=async name=>page.getByRole('button',{name,exact:true}).click();
 const assertText=async text=>{const body=page.domSnapshot ? await page.domSnapshot() : await page.locator('body').innerText();if(!body.includes(text))throw Error('Missing: '+text)};
 const enabled=async name=>{for(const el of await page.getByRole('button',{name,exact:true}).all())if(await el.isEnabled()){await el.click();return}throw Error('No enabled '+name)};
 await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption({label:'1 · Full journey — draft, submit with defects, send-back, v2, approvals, disposition'});
 await click('Owner'); await click('Reset scenario'); await click('BU SPOC'); await click('Open case'); await click('Run checks & submit'); await assertText('3 check(s) flagged'); await click('Submit anyway');
 await click('AI/COE'); await enabled('Send back'); await page.getByRole('combobox',{name:'Artifact the owner must correct *',exact:true}).selectOption('brd'); await page.getByRole('textbox',{name:'What specifically has to change *',exact:true}).fill('Add AUC and precision recall with the denominator and operating threshold.'); await click('Send back to owner');
 await click('Owner'); await page.getByRole('tab',{name:'Documents 9',exact:true}).click(); await page.getByRole('row').filter({hasText:'BRD_ChurnScoring_v1.0.docx'}).getByRole('button',{name:'Change',exact:true}).click(); await page.getByRole('radio',{name:'BRD_ChurnScoring_v1.1.docx Complete — AUC and precision–recall with denominator and operating threshold. Clean',exact:true}).check(); await click('Apply to slot'); await click('Run checks & submit'); await click('Submit anyway');
 for(const role of ['AI/COE','DPO','IT/Security']){await click(role);await enabled('Approve lane');await click('Approve lane anyway')}
 await assertText('All lanes approved · awaiting disposition');
 for(const role of ['IT/Security','DPO']){await click(role);await enabled('Dispose');await page.getByRole('radio',{name:'Waived with reason The gap stands and is accepted for this submission. The reason is mandatory and is recorded against you.',exact:true}).check();await page.getByRole('textbox',{name:'Reason (required)',exact:true}).fill('Synthetic demo review accepts the documented gap for this submission only.');await click('Record disposition')}
 await assertText('Three current-version lane approvals are recorded and every finding on Submission v2 is disposed.'); return {journey:'PASS',submission:2};
}

export async function runAdditionalChecks(page){const click=async name=>page.getByRole('button',{name,exact:true}).click();const text=async value=>{if(!(page.domSnapshot ? await page.domSnapshot() : await page.locator('body').innerText()).includes(value))throw Error('Missing '+value)};await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption({label:'1 · Full journey — draft, submit with defects, send-back, v2, approvals, disposition'});await click('Owner');await click('Reset scenario');await click('New case');await click('Create draft');await text('at least 4');await page.getByRole('textbox',{name:'Case name *',exact:true}).fill('Synthetic team demo');await page.getByRole('radio',{name:'Unknown — no register ID is available',exact:true}).check();await click('Create draft');await text('Synthetic team demo');await text('Unknown');await text('N/A');await click('Admin');await click('Administration');await page.getByRole('textbox',{name:'Pack template version',exact:true}).fill('1.5');await click('Publish revision');await text('Rev 4 · pack template 1.5');for(const width of ['834','390','1440']){await click(width);await text('Template and thresholds')};await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption({label:'4 · Quality checks unavailable'});await click('Run checks & submit');await text('No clean pass is recorded');await click('Submit anyway');await text('Findings 3');await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption({label:'3 · Checklist template v2.0 isolation (SL2.1 must not carry over)'});await text('Extraction accuracy is not a hallucination rate');await text('those figures do not carry over');await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption({label:'1 · Full journey — draft, submit with defects, send-back, v2, approvals, disposition'});await click('Owner');await click('Reset scenario');return {newCase:'PASS',adminPublish:'PASS',widthControls:'PASS',qcOutage:'PASS',templateIsolation:'PASS',reset:'PASS'}}
