-- migration: 0000_w1_00_substrate
-- ticket: W1-00
-- rewrites frozen rows: no
-- rollback expectation: additive; first migration, creates the W0-04 base schema
--
-- Generated by drizzle-kit from server/src/db/schema (tables, constraints, indexes) and completed by hand with the
-- W0-04 immutability triggers, the projection write gate and the role grants. Forward-only; never edited after merge.
-- Applied only by `npm run migrate` as rai_owner (DATABASE_MIGRATE_URL).
CREATE TABLE "case" (
	"id" uuid PRIMARY KEY NOT NULL,
	"registry_id" text NOT NULL,
	"source_record_id" text NOT NULL,
	"use_case_name" text NOT NULL,
	"business_unit" text NOT NULL,
	"business_owner" text NOT NULL,
	"technical_owner" text NOT NULL,
	"use_case_group" text NOT NULL,
	"risk_tier" text,
	"privacy_status" text DEFAULT 'pending' NOT NULL,
	"security_status" text DEFAULT 'pending' NOT NULL,
	"rai_status" text DEFAULT 'pending' NOT NULL,
	"ai_readiness_status" text DEFAULT 'not_ready' NOT NULL,
	"vendor_involved" boolean NOT NULL,
	"model_type" text NOT NULL,
	"owner_subject_id" text NOT NULL,
	"business_unit_id" text NOT NULL,
	"desk_status" text DEFAULT 'draft' NOT NULL,
	"current_version_id" uuid,
	"draft_version_id" uuid,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "case_model_type_check" CHECK ("case"."model_type" IN ('llm', 'classic_ml', 'other')),
	CONSTRAINT "case_desk_status_check" CHECK ("case"."desk_status" IN ('draft', 'in_review', 'ready')),
	CONSTRAINT "case_risk_tier_check" CHECK ("case"."risk_tier" IS NULL OR "case"."risk_tier" IN ('high', 'medium', 'low')),
	CONSTRAINT "case_privacy_status_check" CHECK ("case"."privacy_status" IN ('pending', 'approved', 'sent_back')),
	CONSTRAINT "case_security_status_check" CHECK ("case"."security_status" IN ('pending', 'approved', 'sent_back')),
	CONSTRAINT "case_rai_status_check" CHECK ("case"."rai_status" IN ('pending', 'approved', 'sent_back')),
	CONSTRAINT "case_ai_readiness_status_check" CHECK ("case"."ai_readiness_status" IN ('not_ready', 'ready')),
	CONSTRAINT "case_row_version_check" CHECK ("case"."row_version" >= 1)
);
--> statement-breakpoint
CREATE TABLE "pack_version" (
	"id" uuid PRIMARY KEY NOT NULL,
	"case_id" uuid NOT NULL,
	"version_number" integer NOT NULL,
	"parent_version_id" uuid,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"stage_context" text NOT NULL,
	"checklist_template_version" text NOT NULL,
	"configuration_revision_id" uuid,
	"frozen_configuration" jsonb,
	"lane_mapping_version" text,
	"lane_mapping" jsonb,
	"submitted_by" text,
	"submitted_role" text,
	"submitted_at" timestamp with time zone,
	"ready_at" timestamp with time zone,
	"manifest_hash" text,
	"submit_correlation_id" text,
	CONSTRAINT "pack_version_stage_context_check" CHECK ("pack_version"."stage_context" IN ('idea', 'pre_build', 'pre_launch')),
	CONSTRAINT "pack_version_submitted_consistency_check" CHECK (("pack_version"."submitted_at" IS NULL) OR ("pack_version"."submitted_by" IS NOT NULL AND "pack_version"."submitted_role" IS NOT NULL AND "pack_version"."configuration_revision_id" IS NOT NULL AND "pack_version"."frozen_configuration" IS NOT NULL AND "pack_version"."lane_mapping_version" IS NOT NULL AND "pack_version"."lane_mapping" IS NOT NULL AND "pack_version"."manifest_hash" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "artifact" (
	"id" uuid PRIMARY KEY NOT NULL,
	"content_hash" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"filename" text NOT NULL,
	"media_type" text NOT NULL,
	"uploaded_by" text NOT NULL,
	"uploaded_role" text NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"case_id" uuid NOT NULL,
	"correlation_id" text NOT NULL,
	"bytes_state" text DEFAULT 'present' NOT NULL,
	CONSTRAINT "artifact_content_hash_check" CHECK ("artifact"."content_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "artifact_size_bytes_check" CHECK ("artifact"."size_bytes" > 0),
	CONSTRAINT "artifact_bytes_state_check" CHECK ("artifact"."bytes_state" IN ('present', 'destroyed'))
);
--> statement-breakpoint
CREATE TABLE "artifact_slot" (
	"id" uuid PRIMARY KEY NOT NULL,
	"version_id" uuid NOT NULL,
	"slot" smallint NOT NULL,
	"state" text NOT NULL,
	"reason" text,
	"artifact_id" uuid,
	"updated_by" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "artifact_slot_slot_check" CHECK ("artifact_slot"."slot" BETWEEN 1 AND 9),
	CONSTRAINT "artifact_slot_state_check" CHECK ("artifact_slot"."state" IN ('attached', 'not_yet', 'not_applicable', 'missing')),
	CONSTRAINT "artifact_slot_reason_check" CHECK ("artifact_slot"."state" <> 'not_applicable' OR "artifact_slot"."reason" IS NOT NULL),
	CONSTRAINT "artifact_slot_artifact_check" CHECK (("artifact_slot"."state" = 'attached' AND "artifact_slot"."artifact_id" IS NOT NULL) OR ("artifact_slot"."state" <> 'attached' AND "artifact_slot"."artifact_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "configuration_revision" (
	"id" uuid PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"revision_number" integer NOT NULL,
	"body" jsonb NOT NULL,
	"published_by" text NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"activation_rule" text NOT NULL,
	"supersedes_id" uuid,
	CONSTRAINT "configuration_revision_kind_check" CHECK ("configuration_revision"."kind" IN ('checklist_templates', 'qc_rules', 'sla', 'calendar', 'operator_recipients', 'use_case_groups', 'risk_rubric', 'group_role_mapping')),
	CONSTRAINT "configuration_revision_activation_rule_check" CHECK ("configuration_revision"."activation_rule" IN ('after_publish')),
	CONSTRAINT "configuration_revision_revision_number_check" CHECK ("configuration_revision"."revision_number" >= 1)
);
--> statement-breakpoint
CREATE TABLE "audit_event" (
	"id" uuid PRIMARY KEY NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "audit_event_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_subject_id" text NOT NULL,
	"actor_role" text NOT NULL,
	"action" text NOT NULL,
	"target_case_id" uuid,
	"target_version_id" uuid,
	"target_ref" jsonb,
	"before_ref" jsonb,
	"after_ref" jsonb,
	"correlation_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idempotency_key" (
	"actor_subject_id" text NOT NULL,
	"key" text NOT NULL,
	"action" text NOT NULL,
	"target_case_id" uuid NOT NULL,
	"request_digest" text NOT NULL,
	"response_status" smallint NOT NULL,
	"response_body" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "idempotency_key_actor_subject_id_key_pk" PRIMARY KEY("actor_subject_id","key")
);
--> statement-breakpoint
ALTER TABLE "case" ADD CONSTRAINT "case_current_version_id_pack_version_id_fk" FOREIGN KEY ("current_version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "case" ADD CONSTRAINT "case_draft_version_id_pack_version_id_fk" FOREIGN KEY ("draft_version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "pack_version" ADD CONSTRAINT "pack_version_case_id_case_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."case"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_version" ADD CONSTRAINT "pack_version_parent_version_id_pack_version_id_fk" FOREIGN KEY ("parent_version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_version" ADD CONSTRAINT "pack_version_configuration_revision_id_configuration_revision_id_fk" FOREIGN KEY ("configuration_revision_id") REFERENCES "public"."configuration_revision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifact" ADD CONSTRAINT "artifact_case_id_case_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."case"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifact_slot" ADD CONSTRAINT "artifact_slot_version_id_pack_version_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifact_slot" ADD CONSTRAINT "artifact_slot_artifact_id_artifact_id_fk" FOREIGN KEY ("artifact_id") REFERENCES "public"."artifact"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "configuration_revision" ADD CONSTRAINT "configuration_revision_supersedes_id_configuration_revision_id_fk" FOREIGN KEY ("supersedes_id") REFERENCES "public"."configuration_revision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_target_case_id_case_id_fk" FOREIGN KEY ("target_case_id") REFERENCES "public"."case"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_target_version_id_pack_version_id_fk" FOREIGN KEY ("target_version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_key" ADD CONSTRAINT "idempotency_key_target_case_id_case_id_fk" FOREIGN KEY ("target_case_id") REFERENCES "public"."case"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "case_registry_id_key" ON "case" USING btree ("registry_id");--> statement-breakpoint
CREATE INDEX "case_owner_subject_id_idx" ON "case" USING btree ("owner_subject_id");--> statement-breakpoint
CREATE INDEX "case_business_unit_id_idx" ON "case" USING btree ("business_unit_id");--> statement-breakpoint
CREATE INDEX "case_desk_status_idx" ON "case" USING btree ("desk_status");--> statement-breakpoint
CREATE UNIQUE INDEX "pack_version_case_id_version_number_key" ON "pack_version" USING btree ("case_id","version_number");--> statement-breakpoint
CREATE UNIQUE INDEX "pack_version_one_open_draft_key" ON "pack_version" USING btree ("case_id") WHERE "pack_version"."submitted_at" IS NULL;--> statement-breakpoint
CREATE INDEX "pack_version_case_id_idx" ON "pack_version" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "artifact_content_hash_idx" ON "artifact" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "artifact_case_id_idx" ON "artifact" USING btree ("case_id");--> statement-breakpoint
CREATE UNIQUE INDEX "artifact_slot_version_id_slot_key" ON "artifact_slot" USING btree ("version_id","slot");--> statement-breakpoint
CREATE UNIQUE INDEX "configuration_revision_kind_revision_number_key" ON "configuration_revision" USING btree ("kind","revision_number");--> statement-breakpoint
CREATE INDEX "configuration_revision_kind_published_at_idx" ON "configuration_revision" USING btree ("kind","published_at");--> statement-breakpoint
CREATE INDEX "audit_event_target_case_id_seq_idx" ON "audit_event" USING btree ("target_case_id","seq");--> statement-breakpoint
CREATE INDEX "audit_event_correlation_id_idx" ON "audit_event" USING btree ("correlation_id");--> statement-breakpoint
CREATE INDEX "audit_event_seq_idx" ON "audit_event" USING btree ("seq");--> statement-breakpoint
CREATE INDEX "idempotency_key_created_at_idx" ON "idempotency_key" USING btree ("created_at");
--> statement-breakpoint
-- ---------------------------------------------------------------------------------------------------------------
-- Hand-written part (W0-04 "Immutability", "Desk-local Case fields and the four status projections", "Audit log").
-- Both the trigger and the grant are required: the trigger protects against a privileged connection (a migration,
-- an operator session); the grant protects against an application bug.
-- ---------------------------------------------------------------------------------------------------------------

-- audit_event: append-only in every state. No UPDATE or DELETE, for any role.
CREATE FUNCTION rai_audit_event_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'rai.append_only' USING DETAIL = 'audit_event rows are never updated or deleted (W0-04, A11)';
END;
$$;--> statement-breakpoint
CREATE TRIGGER audit_event_append_only BEFORE UPDATE OR DELETE ON "audit_event"
  FOR EACH ROW EXECUTE FUNCTION rai_audit_event_append_only();--> statement-breakpoint

-- configuration_revision: never updated or deleted once published (slice 1 has no unpublished revisions).
CREATE FUNCTION rai_configuration_revision_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.published_at IS NOT NULL THEN
    RAISE EXCEPTION 'rai.frozen_revision' USING DETAIL = 'a published configuration_revision is immutable (W0-04, L12)';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER configuration_revision_frozen BEFORE UPDATE OR DELETE ON "configuration_revision"
  FOR EACH ROW EXECUTE FUNCTION rai_configuration_revision_frozen();--> statement-breakpoint

-- pack_version: mutable while submitted_at IS NULL (the submit freeze is the last such update); once submitted,
-- the only permitted change is ready_at from NULL to a value with every other column unchanged (W0-06 9.2).
CREATE FUNCTION rai_pack_version_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  probe "pack_version"%ROWTYPE;
BEGIN
  IF OLD.submitted_at IS NULL THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'rai.frozen_version' USING DETAIL = 'a submitted pack_version is never deleted (W0-04, A07)';
  END IF;
  probe := NEW;
  probe.ready_at := OLD.ready_at;
  IF OLD.ready_at IS NULL AND NEW.ready_at IS NOT NULL AND probe IS NOT DISTINCT FROM OLD THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'rai.frozen_version' USING DETAIL = 'a submitted pack_version is immutable except ready_at once (W0-06 9.2)';
END;
$$;--> statement-breakpoint
CREATE TRIGGER pack_version_frozen BEFORE UPDATE OR DELETE ON "pack_version"
  FOR EACH ROW EXECUTE FUNCTION rai_pack_version_frozen();--> statement-breakpoint

-- artifact_slot: mutable only while the parent version is a draft.
CREATE FUNCTION rai_artifact_slot_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  parent_submitted_at timestamptz;
BEGIN
  SELECT submitted_at INTO parent_submitted_at FROM "pack_version" WHERE id = OLD.version_id;
  IF parent_submitted_at IS NOT NULL THEN
    RAISE EXCEPTION 'rai.frozen_version' USING DETAIL = 'artifact_slot rows of a submitted version are immutable (W0-04, A07)';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER artifact_slot_frozen BEFORE UPDATE OR DELETE ON "artifact_slot"
  FOR EACH ROW EXECUTE FUNCTION rai_artifact_slot_frozen();--> statement-breakpoint

-- artifact: immutable once inserted; bytes_state is the single D08 exception, gated by rai.retention_write.
CREATE FUNCTION rai_artifact_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  probe "artifact"%ROWTYPE;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'rai.frozen_artifact' USING DETAIL = 'artifact rows are never deleted (W0-04)';
  END IF;
  probe := NEW;
  probe.bytes_state := OLD.bytes_state;
  IF probe IS DISTINCT FROM OLD THEN
    RAISE EXCEPTION 'rai.frozen_artifact' USING DETAIL = 'artifact rows are immutable (W0-04)';
  END IF;
  IF NEW.bytes_state IS DISTINCT FROM OLD.bytes_state AND current_setting('rai.retention_write', true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION 'rai.frozen_artifact' USING DETAIL = 'bytes_state changes only under rai.retention_write (D08)';
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER artifact_frozen BEFORE UPDATE OR DELETE ON "artifact"
  FOR EACH ROW EXECUTE FUNCTION rai_artifact_frozen();--> statement-breakpoint

-- case: the four projections and risk_tier are written only by the workflow, inside a transaction that executed
-- SET LOCAL rai.workflow_write = 'on' (W0-04 fields rule, three-layer enforcement, layer 3).
CREATE FUNCTION rai_case_projection_gate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.privacy_status IS DISTINCT FROM OLD.privacy_status
      OR NEW.security_status IS DISTINCT FROM OLD.security_status
      OR NEW.rai_status IS DISTINCT FROM OLD.rai_status
      OR NEW.ai_readiness_status IS DISTINCT FROM OLD.ai_readiness_status
      OR NEW.risk_tier IS DISTINCT FROM OLD.risk_tier)
     AND current_setting('rai.workflow_write', true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION 'rai.projection_write_forbidden' USING DETAIL = 'projections are written only by the workflow (W0-04 fields)';
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER case_projection_gate BEFORE UPDATE ON "case"
  FOR EACH ROW EXECUTE FUNCTION rai_case_projection_gate();--> statement-breakpoint

-- Grants (W0-04 "Database roles"). rai_operator is a member of rai_app (docker/postgres/init) and receives only
-- what this block adds. Nothing else is granted; no role but rai_owner may run DDL.
GRANT SELECT, INSERT ON "case", "pack_version", "artifact", "artifact_slot", "configuration_revision", "audit_event", "idempotency_key" TO rai_app;--> statement-breakpoint
GRANT UPDATE ON "case", "pack_version", "artifact_slot", "artifact" TO rai_app;--> statement-breakpoint
GRANT DELETE ON "idempotency_key" TO rai_operator;--> statement-breakpoint
GRANT USAGE ON SCHEMA drizzle TO rai_app;--> statement-breakpoint
GRANT SELECT ON drizzle.__drizzle_migrations TO rai_app;
