-- migration: 0001_w1_01_session
-- ticket: W1-01
-- rewrites frozen rows: no
-- rollback expectation: additive; creates the W0-03 section 6.3 session table and its grants
--
-- Generated by drizzle-kit from server/src/db/schema/session.ts and completed by hand with the grants and the
-- locale / identity_mode checks. Forward-only; never edited after merge. Applied only by `npm run migrate`.
CREATE TABLE "session" (
	"id" uuid PRIMARY KEY NOT NULL,
	"token_hash" text NOT NULL,
	"subject_id" text NOT NULL,
	"principal" jsonb NOT NULL,
	"identity_mode" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"locale" text DEFAULT 'th' NOT NULL,
	CONSTRAINT "session_identity_mode_check" CHECK ("session"."identity_mode" IN ('fixture', 'local-google', 'network', 'production')),
	CONSTRAINT "session_locale_check" CHECK ("session"."locale" IN ('th', 'en')),
	CONSTRAINT "session_token_hash_check" CHECK ("session"."token_hash" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "session_token_hash_key" ON "session" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "session_subject_id_idx" ON "session" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint

-- Grants. Session rows are W0-03 operational data (section 6.3: "not audit, and are not retained"): rai_app reads,
-- creates and updates them (last_seen_at, revoked_at, locale); only rai_operator deletes expired and revoked rows,
-- through `npm run db:cleanup` and `reset` (W0-04 "Database roles": rai_app deletes nothing).
GRANT SELECT, INSERT, UPDATE ON "session" TO rai_app;--> statement-breakpoint
GRANT DELETE ON "session" TO rai_operator;
