-- migration: 0002_w1_09_fixture_set
-- ticket: W1-09
-- rewrites frozen rows: no
-- rollback expectation: additive; one new table, no change to existing tables, triggers or grants
--
-- Generated by drizzle-kit from server/src/db/schema/fixture-set.ts and completed by hand with the grant. The
-- `fixture_set` row records which synthetic fixture set `npm run fixtures:load` wrote (W0-02 section 8.3; W0-08 8.7),
-- so evidence that cites `fixture set <name>@<version> <sha256[0:12]>` can be checked against the database.
-- Development and test only by use: no route reads or writes it. Numbered 0002 because 0001_w1_01_session merged first.
-- Forward-only; never edited after merge.
CREATE TABLE "fixture_set" (
	"name" text NOT NULL,
	"version" text NOT NULL,
	"sha256" text NOT NULL,
	"loaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"correlation_id" text NOT NULL,
	CONSTRAINT "fixture_set_name_version_pk" PRIMARY KEY("name","version"),
	CONSTRAINT "fixture_set_sha256_check" CHECK ("fixture_set"."sha256" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
-- Grant (W0-04 "Database roles"): the loader runs as rai_operator (a member of rai_app) or rai_owner; the
-- application role may read and insert, never update or delete, like every other business table.
GRANT SELECT, INSERT ON "fixture_set" TO rai_app;
