-- migration: 0003_w1_02_registry_counter
-- ticket: W1-02
-- rewrites frozen rows: no
-- rollback expectation: additive; one new table, no change to existing tables, triggers or grants
--
-- Generated by drizzle-kit from server/src/db/schema/registry-counter.ts and completed by hand with the grant.
-- The per-year counter behind `case.registry_id` (W0-04: "RAI-YYYY-NNNN, allocated from a per-year sequence inside
-- the create transaction"). The create transaction upserts the year row and takes `last + 1` under the row lock the
-- UPDATE acquires (W1-02, server/src/cases/repository.ts). Year 2000 is reserved for fixtures (W0-02 section 8.3)
-- and excluded by the check. Numbered 0003 after W1-09's 0002. Forward-only; never edited after merge.
CREATE TABLE "registry_counter" (
	"year" integer PRIMARY KEY NOT NULL,
	"last" integer NOT NULL,
	CONSTRAINT "registry_counter_year_check" CHECK ("registry_counter"."year" BETWEEN 2001 AND 9999),
	CONSTRAINT "registry_counter_last_check" CHECK ("registry_counter"."last" BETWEEN 0 AND 9999)
);
--> statement-breakpoint
-- Grant (W0-04 "Database roles"): the application role reads, inserts and updates the counter; nobody deletes it.
GRANT SELECT, INSERT, UPDATE ON "registry_counter" TO rai_app;
