-- migration: 0004_w2_01_notification
-- ticket: W2-01
-- rewrites frozen rows: no
-- rollback expectation: additive; one new table, no change to existing tables, triggers or grants
--
-- Generated by drizzle-kit from server/src/db/schema/notification.ts and completed by hand with the W0-04
-- delivery-column UPDATE gate, DELETE raise and the role grants. Forward-only; never edited after merge.
-- Applied only by `npm run migrate` as rai_owner (DATABASE_MIGRATE_URL).
CREATE TABLE "notification" (
	"id" uuid PRIMARY KEY NOT NULL,
	"event" text NOT NULL,
	"version_id" uuid,
	"case_id" uuid,
	"lane" text NOT NULL,
	"recipient" text NOT NULL,
	"deep_link_path" text NOT NULL,
	"template_key" text NOT NULL,
	"template_params" jsonb NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone,
	"last_error_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"correlation_id" text NOT NULL,
	CONSTRAINT "notification_event_check" CHECK ("notification"."event" IN ('lane_open', 'send_back', 'ready', 'sla_breach_digest')),
	CONSTRAINT "notification_status_check" CHECK ("notification"."status" IN ('queued', 'sent', 'failed')),
	CONSTRAINT "notification_attempts_check" CHECK ("notification"."attempts" >= 0)
);
--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_version_id_pack_version_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."pack_version"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_case_id_case_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."case"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "notification_event_version_lane_recipient_key" ON "notification" USING btree ("event","version_id","lane","recipient");--> statement-breakpoint
CREATE INDEX "notification_status_next_attempt_at_idx" ON "notification" USING btree ("status","next_attempt_at");--> statement-breakpoint
CREATE INDEX "notification_correlation_id_idx" ON "notification" USING btree ("correlation_id");--> statement-breakpoint

-- notification: INSERT freely; UPDATE only the four W3-04 delivery columns; never DELETE (W0-04 immutability).
CREATE FUNCTION rai_notification_delivery_only() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  probe "notification"%ROWTYPE;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'rai.append_only' USING DETAIL = 'notification rows are never deleted (W0-04)';
  END IF;
  probe := NEW;
  probe.status := OLD.status;
  probe.attempts := OLD.attempts;
  probe.next_attempt_at := OLD.next_attempt_at;
  probe.last_error_code := OLD.last_error_code;
  IF probe IS DISTINCT FROM OLD THEN
    RAISE EXCEPTION 'rai.notification_immutable' USING DETAIL = 'notification columns other than status, attempts, next_attempt_at, last_error_code are immutable (W0-04, W3-04)';
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER notification_delivery_only BEFORE UPDATE OR DELETE ON "notification"
  FOR EACH ROW EXECUTE FUNCTION rai_notification_delivery_only();--> statement-breakpoint

-- Grants (W0-04 "Database roles"): rai_app inserts and updates delivery columns; nobody deletes.
GRANT SELECT, INSERT, UPDATE ON "notification" TO rai_app;
