-- migration: 0011_w7_03_migration_class
-- ticket: W7-03 (W7 plan section 3.3)
-- rewrites frozen rows: no
-- rollback expectation: additive; one new table, no change to existing tables, triggers or grants
--
-- schema_migration_class: the rollback class (W0-04: additive, restore-required, copy-forward) of every applied
-- migration, written only by `npm run migrate` (db/migrate.ts recordMigrationClasses) from the build's
-- MIGRATION_CLASSES and back-filled for migrations applied before this one. Readiness and release:check-rollback
-- read it by hash. Append-only; rai_app and rai_operator may only SELECT.
-- Generated by drizzle-kit from server/src/db/schema/schema-migration-class.ts and completed by hand with the guard
-- and the grants. Forward-only; never edited after merge. Applied only by `npm run migrate` as rai_owner.
CREATE TABLE "schema_migration_class" (
	"hash" text PRIMARY KEY NOT NULL,
	"tag" text NOT NULL,
	"rollback_class" text NOT NULL,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "schema_migration_class_tag_unique" UNIQUE("tag"),
	CONSTRAINT "schema_migration_class_rollback_class_check" CHECK ("schema_migration_class"."rollback_class" IN ('additive', 'restore-required', 'copy-forward'))
);
--> statement-breakpoint

-- Append-only: no UPDATE, no DELETE (a recorded class never changes; the writer fails on a changed map instead).
CREATE FUNCTION rai_schema_migration_class_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'rai.append_only' USING DETAIL = 'schema_migration_class rows are never updated or deleted (W7-03)';
END;
$$;--> statement-breakpoint
CREATE TRIGGER schema_migration_class_guard BEFORE UPDATE OR DELETE ON "schema_migration_class"
  FOR EACH ROW EXECUTE FUNCTION rai_schema_migration_class_guard();--> statement-breakpoint

GRANT SELECT ON "schema_migration_class" TO rai_app;--> statement-breakpoint
GRANT SELECT ON "schema_migration_class" TO rai_operator;
