-- migration: 0013_w7_06_subject_profile
-- ticket: W7-06 (W7 plan section 4.1)
-- rewrites frozen rows: no
-- rollback expectation: additive; one new table, no change to existing tables, triggers or grants
--
-- subject_profile: one row per subject that has signed in outside fixture mode (subject, identity mode, email,
-- display name, role snapshot, first seen, last sign-in), upserted by the session store inside the sign-in
-- transaction. Read by the case subject directory and, from W7-07, the mail recipient directory. Operational data,
-- not evidence: no trigger, not in the frozen digest. rai_app may SELECT, INSERT and UPDATE; nobody may DELETE at
-- runtime (removal is a D08 retention question). Synthetic principals only until D08.
-- Generated by drizzle-kit from server/src/db/schema/subject-profile.ts and completed by hand with the grants.
-- Forward-only; never edited after merge. Applied only by `npm run migrate` as rai_owner.
CREATE TABLE "subject_profile" (
	"subject_id" text PRIMARY KEY NOT NULL,
	"identity_mode" text NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"roles" jsonb NOT NULL,
	"first_seen_at" timestamp with time zone NOT NULL,
	"last_sign_in_at" timestamp with time zone NOT NULL,
	CONSTRAINT "subject_profile_identity_mode_check" CHECK ("subject_profile"."identity_mode" IN ('local-google', 'network', 'production'))
);--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE ON "subject_profile" TO rai_app;
