// W0-08 section 8.4, verbatim: the 33 synthetic documents of fixture set slice1-synthetic (W1-09 owns this table).
// Fixture document ids are `fx-doc-<case number>-<slot>`; the filename is the artifact's `filename` metadata (NFC);
// the object key is the content hash, recorded per document in data/manifest.json by `fixtures:generate`.
// Content of every document (W0-08 8.4): the sentinel, the fixture id, the case id, the slot number and name, one
// Thai line and the provenance sentence. Nothing else. No bytes are committed: `fixtures:generate` writes them
// from these rows into the gitignored output directory (W0-08 8.1 rule 2).

import type { SlotNumber } from '@rai/shared/schemas/pack';
import { ALLOWED_MEDIA_TYPES, type AllowedMediaType } from '@rai/shared/schemas/artifacts';
import { fixtureUuid } from '../ids.js';

/** The greppable provenance marker every generated document carries in plain bytes (W0-08 8.1 rule 3). */
export const FIXTURE_SENTINEL = 'RAI-DESK-SYNTHETIC-FIXTURE' as const;
/** The Thai line every document carries: "synthetic document for testing; not a real document". */
export const FIXTURE_THAI_LINE = 'เอกสารสังเคราะห์สำหรับการทดสอบ ไม่ใช่เอกสารจริง' as const;
export const FIXTURE_PROVENANCE_SENTENCE =
  'Generated by rai-web/fixtures. Not a real document. Contains no real data.' as const;

export type FixtureDocumentKind = 'pdf' | 'docx' | 'xlsx' | 'png' | 'jpeg';
export type FixtureSizeClass = 'small' | 'medium';

export const MEDIA_TYPE_BY_KIND: Readonly<Record<FixtureDocumentKind, AllowedMediaType>> = Object.freeze({
  pdf: ALLOWED_MEDIA_TYPES[0],
  docx: ALLOWED_MEDIA_TYPES[1],
  xlsx: ALLOWED_MEDIA_TYPES[2],
  png: ALLOWED_MEDIA_TYPES[3],
  jpeg: ALLOWED_MEDIA_TYPES[4],
});

/** The nine pack slots by number (source spec "Pack and lanes"); the document text names the slot it fills. */
export const SLOT_NAMES: Readonly<Record<SlotNumber, string>> = Object.freeze({
  1: 'Risk screening',
  2: 'Privacy checklist',
  3: 'DPA',
  4: 'SOW',
  5: 'BRD',
  6: 'AI architecture',
  7: 'Security assessment',
  8: 'RAI deployment checklist',
  9: 'Other supporting',
});

export interface FixtureDocument {
  fixtureDocumentId: string; // fx-doc-<case number>-<slot>
  /** The UUID the loader writes as artifact.id (deterministic; fixtureUuid). */
  artifactId: string;
  caseNumber: '0001' | '0002' | '0003' | '0004' | '0005';
  slot: SlotNumber;
  filename: string; // NFC
  kind: FixtureDocumentKind;
  sizeClass: FixtureSizeClass;
  note?: string;
}

function doc(
  caseNumber: FixtureDocument['caseNumber'],
  slot: SlotNumber,
  filename: string,
  kind: FixtureDocumentKind,
  sizeClass: FixtureSizeClass = 'small',
  note?: string,
): FixtureDocument {
  const fixtureDocumentId = `fx-doc-${caseNumber}-${String(slot).padStart(2, '0')}`;
  const row: FixtureDocument = {
    fixtureDocumentId,
    artifactId: fixtureUuid(fixtureDocumentId),
    caseNumber,
    slot,
    filename: filename.normalize('NFC'),
    kind,
    sizeClass,
  };
  return note === undefined ? row : { ...row, note };
}

/** W0-08 8.4 names this file as "the Thai-named file": NFC, 34 code points, 82 bytes UTF-8. */
export const THAI_NAMED_FIXTURE_DOCUMENT_ID = 'fx-doc-0002-09' as const;

export const FIXTURE_DOCUMENTS: readonly FixtureDocument[] = Object.freeze([
  doc('0001', 1, 'RiskScreening_ChurnScoring.pdf', 'pdf'),
  doc('0001', 2, 'PrivacyChecklist_v1.0.xlsx', 'xlsx'),
  doc('0001', 5, 'BRD_ChurnScoring_v1.0.docx', 'docx'),
  doc('0001', 6, 'Architecture_Overview.pdf', 'pdf'),
  doc('0001', 7, 'SecurityAssessment_signed.pdf', 'pdf'),
  doc('0001', 8, 'DeploymentChecklist_v1.0.xlsx', 'xlsx'),
  doc('0001', 9, 'DataFlow_Diagram.png', 'png', 'small', 'PNG 64 x 64'),
  doc('0002', 1, 'RiskScreening_StoreAssistant.pdf', 'pdf'),
  doc('0002', 2, 'PrivacyChecklist_v1.1.xlsx', 'xlsx'),
  doc(
    '0002',
    3,
    'DPA_PartnerVendor_signed.pdf',
    'pdf',
    'medium',
    'about 2 MiB of generated filler so the transfer path is exercised above one TCP window',
  ),
  doc('0002', 4, 'SOW_PartnerVendor_2026.pdf', 'pdf'),
  doc('0002', 5, 'BRD_StoreAssistant_v2.0.docx', 'docx'),
  doc('0002', 6, 'Architecture_StoreAssistant.pdf', 'pdf'),
  doc('0002', 7, 'SecurityAssessment_StoreAssistant.pdf', 'pdf'),
  doc('0002', 8, 'DeploymentChecklist_v2.0.xlsx', 'xlsx'),
  doc('0002', 9, 'เอกสารประกอบ_ผู้ให้บริการ_2569.pdf', 'pdf', 'small', 'the Thai-named file'),
  doc('0003', 1, 'RiskScreening_DispatchOptimiser.pdf', 'pdf'),
  doc('0003', 2, 'PrivacyChecklist_Dispatch.xlsx', 'xlsx'),
  doc('0003', 5, 'BRD_DispatchOptimiser_v0.9.docx', 'docx'),
  doc('0003', 6, 'Architecture_Dispatch.pdf', 'pdf'),
  doc('0003', 9, 'Whiteboard_Photo.jpg', 'jpeg', 'small', 'JPEG 16 x 16 baseline'),
  doc('0004', 1, 'RiskScreening_FAQAssistant.pdf', 'pdf'),
  doc('0004', 2, 'PrivacyChecklist_FAQAssistant.xlsx', 'xlsx'),
  doc('0004', 3, 'DPA_FAQVendor_draft.pdf', 'pdf'),
  doc('0004', 5, 'BRD_FAQAssistant_idea.docx', 'docx'),
  doc('0004', 6, 'Architecture_FAQAssistant_sketch.png', 'png', 'small', 'PNG 64 x 64'),
  doc('0004', 7, 'SecurityAssessment_FAQAssistant_pre.pdf', 'pdf'),
  doc('0005', 1, 'RiskScreening_RecruitmentScreening.pdf', 'pdf'),
  doc('0005', 2, 'PrivacyChecklist_Recruitment.xlsx', 'xlsx'),
  doc('0005', 5, 'BRD_RecruitmentScreening_v1.0.docx', 'docx'),
  doc('0005', 6, 'Architecture_Recruitment.pdf', 'pdf'),
  doc('0005', 7, 'SecurityAssessment_Recruitment.pdf', 'pdf'),
  doc('0005', 8, 'DeploymentChecklist_Recruitment.xlsx', 'xlsx'),
]);

export function findFixtureDocument(fixtureDocumentId: string): FixtureDocument | undefined {
  return FIXTURE_DOCUMENTS.find((d) => d.fixtureDocumentId === fixtureDocumentId);
}

/** The plain-text lines every generated document carries (W0-08 8.4), in order. */
export function documentTextLines(document: FixtureDocument): string[] {
  return [
    FIXTURE_SENTINEL,
    `Fixture ID: ${document.fixtureDocumentId}`,
    `Case: RAI-2000-${document.caseNumber}`,
    `Slot ${document.slot}: ${SLOT_NAMES[document.slot]}`,
    FIXTURE_THAI_LINE,
    FIXTURE_PROVENANCE_SENTENCE,
  ];
}
